FROM oven/bun:1-slim AS builder

ARG OAUTH_PROVIDERS

WORKDIR /app

COPY bun.lock package.json ./
RUN bun install

COPY . .

RUN bun quasar prepare
RUN bun run build:front
RUN bun run build:admin

FROM caddy:2-alpine AS runner

WORKDIR /srv

COPY --from=builder /app/dist/pwa   ./front
COPY --from=builder /app/dist/spa   ./admin

COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 8080 8081
