FROM oven/bun:1-slim AS builder

WORKDIR /app

COPY bun.lock package.json ./
RUN bun install

COPY . .

RUN bun quasar prepare
RUN bun run build:server

FROM oven/bun:1-slim AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/dist/server .

EXPOSE 3000

CMD ["bun", "index.js"]
