import { drizzleZeroConfig } from 'drizzle-zero'
import * as schema from './src-server/schema'

export default drizzleZeroConfig(schema, {
  tables: {
    user: true,
    workspace: true,
    member: true,
    workspaceInvitation: true,
    message: true,
    entity: true,
    messageEntity: true,
    toolCall: true,
    searchRecord: true,
    chat: true,
    channel: true,
    model: true,
    assistant: true,
    page: true,
    pagePatch: true,
    provider: true,
    item: true,
    shortcut: true,
    search: true,
    translation: true,
    translationRecord: true,
    mcpPlugin: true,
    userData: true,
    memberData: true,
    plan: true,
    planPrice: true,
    blob: {
      id: true,
      size: true,
      sha256: true,
    },
    usage: true,
    order: true,
    entityAccess: true,
    globalSettings: true,
  },
})
