// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { ZeroCustomType } from "@krytro/drizzle-zero";
import type { default as zeroSchema } from "../drizzle-zero.config";

const assistantTable = {
  name: "assistant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "rootId"
      >,
    },
    prompt: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "prompt"
      >,
    },
    promptTemplate: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "promptTemplate"
      >,
    },
    promptRole: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "promptRole"
      >,
    },
    contextNum: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "contextNum"
      >,
    },
    streamSettings: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "streamSettings"
      >,
    },
    plugins: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "plugins"
      >,
    },
    modelId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "assistant",
        "modelId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const blobTable = {
  name: "blob",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "blob",
        "id"
      >,
    },
    sha256: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "blob",
        "sha256"
      >,
    },
    size: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "blob",
        "size"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const channelTable = {
  name: "channel",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "channel",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "channel",
        "rootId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const chatTable = {
  name: "chat",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "rootId"
      >,
    },
    msgTree: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "msgTree"
      >,
    },
    msgRoute: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "msgRoute"
      >,
    },
    plugins: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "plugins"
      >,
    },
    modelId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "chat",
        "modelId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const entityTable = {
  name: "entity",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "rootId"
      >,
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "parentId"
      >,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "type"
      >,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "name"
      >,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "avatar"
      >,
    },
    conf: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "conf"
      >,
    },
    sortPriority: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "sortPriority"
      >,
    },
    hidden: {
      type: "boolean",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "hidden"
      >,
    },
    pubRoot: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entity",
        "pubRoot"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const entityAccessTable = {
  name: "entityAccess",
  columns: {
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entityAccess",
        "userId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entityAccess",
        "entityId"
      >,
    },
    time: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "entityAccess",
        "time"
      >,
    },
  },
  primaryKey: ["entityId", "userId"],
} as const;
const globalSettingsTable = {
  name: "globalSettings",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "id"
      >,
    },
    defaultChatModel: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "defaultChatModel"
      >,
    },
    defaultChatTitleModel: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "defaultChatTitleModel"
      >,
    },
    defaultTranslationModel: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "defaultTranslationModel"
      >,
    },
    defaultSearchChatModel: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "defaultSearchChatModel"
      >,
    },
    freeModelReqLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "freeModelReqLimit"
      >,
    },
    freeModelLimitWindow: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "freeModelLimitWindow"
      >,
    },
    maxWorkspacesPerUser: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "maxWorkspacesPerUser"
      >,
    },
    oauthProviders: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "globalSettings",
        "oauthProviders"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const itemTable = {
  name: "item",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "rootId"
      >,
    },
    text: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "text"
      >,
    },
    language: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "language"
      >,
    },
    blobId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "blobId"
      >,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "item",
        "mimeType"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const mcpPluginTable = {
  name: "mcpPlugin",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "rootId"
      >,
    },
    enabled: {
      type: "boolean",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "enabled"
      >,
    },
    transport: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "transport"
      >,
    },
    requestTimeout: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "requestTimeout"
      >,
    },
    resetTimeoutOnProgress: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "resetTimeoutOnProgress"
      >,
    },
    keepAliveTimeout: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "mcpPlugin",
        "keepAliveTimeout"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "id"
      >,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "workspaceId"
      >,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "userId"
      >,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "role"
      >,
    },
    leftDirId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "leftDirId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const messageTable = {
  name: "message",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "rootId"
      >,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "type"
      >,
    },
    assistantId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "assistantId"
      >,
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "userId"
      >,
    },
    sentAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "sentAt"
      >,
    },
    editedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "editedAt"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "entityId"
      >,
    },
    text: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "text"
      >,
    },
    reasoning: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "reasoning"
      >,
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "error"
      >,
    },
    warnings: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "warnings"
      >,
    },
    usage: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "usage"
      >,
    },
    modelName: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "message",
        "modelName"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const messageEntityTable = {
  name: "messageEntity",
  columns: {
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "messageEntity",
        "rootId"
      >,
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "messageEntity",
        "messageId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "messageEntity",
        "entityId"
      >,
    },
  },
  primaryKey: ["messageId", "entityId"],
} as const;
const modelTable = {
  name: "model",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "rootId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "entityId"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "name"
      >,
    },
    label: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "label"
      >,
    },
    caption: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "caption"
      >,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "avatar"
      >,
    },
    inputTypes: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "inputTypes"
      >,
    },
    settings: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "settings"
      >,
    },
    inputPrice: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "inputPrice"
      >,
    },
    outputPrice: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "outputPrice"
      >,
    },
    providerOptions: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "model",
        "providerOptions"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const orderTable = {
  name: "order",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "id"
      >,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "workspaceId"
      >,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "planId"
      >,
    },
    planInterval: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "planInterval"
      >,
    },
    provider: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "provider"
      >,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "amount"
      >,
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "order",
        "completedAt"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const pageTable = {
  name: "page",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "page",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "page",
        "rootId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const pagePatchTable = {
  name: "pagePatch",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "pagePatch",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "pagePatch",
        "rootId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "pagePatch",
        "entityId"
      >,
    },
    patch: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "pagePatch",
        "patch"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const planTable = {
  name: "plan",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "id"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "name"
      >,
    },
    maxMembers: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "maxMembers"
      >,
    },
    storageLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "storageLimit"
      >,
    },
    fileSizeLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "fileSizeLimit"
      >,
    },
    quotaLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "plan",
        "quotaLimit"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const planPriceTable = {
  name: "planPrice",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "id"
      >,
    },
    enabled: {
      type: "boolean",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "enabled"
      >,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "planId"
      >,
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "provider"
      >,
    },
    interval: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "interval"
      >,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "amount"
      >,
    },
    priceId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "planPrice",
        "priceId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const providerTable = {
  name: "provider",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "provider",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "provider",
        "rootId"
      >,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "provider",
        "type"
      >,
    },
    settings: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "provider",
        "settings"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const searchTable = {
  name: "search",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "search",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "search",
        "rootId"
      >,
    },
    currentIndex: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "search",
        "currentIndex"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const searchRecordTable = {
  name: "searchRecord",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "searchRecord",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "searchRecord",
        "rootId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "searchRecord",
        "entityId"
      >,
    },
    q: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "searchRecord",
        "q"
      >,
    },
    results: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "searchRecord",
        "results"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const shortcutTable = {
  name: "shortcut",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "shortcut",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "shortcut",
        "rootId"
      >,
    },
    dirId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "shortcut",
        "dirId"
      >,
    },
    type: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "shortcut",
        "type"
      >,
    },
    action: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "shortcut",
        "action"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const toolCallTable = {
  name: "toolCall",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "rootId"
      >,
    },
    pluginId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "pluginId"
      >,
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "messageId"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "name"
      >,
    },
    input: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "input"
      >,
    },
    result: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "result"
      >,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "status"
      >,
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "toolCall",
        "error"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const translationTable = {
  name: "translation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translation",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translation",
        "rootId"
      >,
    },
    currentIndex: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translation",
        "currentIndex"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const translationRecordTable = {
  name: "translationRecord",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "id"
      >,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "rootId"
      >,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "entityId"
      >,
    },
    input: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "input"
      >,
    },
    output: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "output"
      >,
    },
    from: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "from"
      >,
    },
    to: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "translationRecord",
        "to"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const usageTable = {
  name: "usage",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "id"
      >,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "workspaceId"
      >,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "userId"
      >,
    },
    modelName: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "modelName"
      >,
    },
    cost: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "cost"
      >,
    },
    details: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "usage",
        "details"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "id"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "name"
      >,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "email"
      >,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "emailVerified"
      >,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "image"
      >,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "role"
      >,
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "banned"
      >,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "banReason"
      >,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "banExpires"
      >,
      serverName: "ban_expires",
    },
    twoFactorEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "twoFactorEnabled"
      >,
      serverName: "two_factor_enabled",
    },
  },
  primaryKey: ["id"],
} as const;
const userDataTable = {
  name: "userData",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "userData",
        "id"
      >,
    },
    lastWorkspaceId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "userData",
        "lastWorkspaceId"
      >,
    },
    perfs: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "userData",
        "perfs"
      >,
    },
    data: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "userData",
        "data"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const workspaceTable = {
  name: "workspace",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "id"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "name"
      >,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "avatar"
      >,
    },
    ownerId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "ownerId"
      >,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "planId"
      >,
    },
    quotaUsed: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "quotaUsed"
      >,
    },
    resetAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "resetAt"
      >,
    },
    remainingMonths: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "remainingMonths"
      >,
    },
    payment: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "payment"
      >,
    },
    storageUsed: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "storageUsed"
      >,
    },
    trashId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "trashId"
      >,
    },
    perfs: {
      type: "json",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "perfs"
      >,
    },
    defaultLeftDirId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspace",
        "defaultLeftDirId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const workspaceInvitationTable = {
  name: "workspaceInvitation",
  columns: {
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "token"
      >,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "workspaceId"
      >,
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "inviterId"
      >,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "role"
      >,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "expiresAt"
      >,
    },
    remainingSeats: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "workspaceInvitation",
        "remainingSeats"
      >,
    },
  },
  primaryKey: ["token"],
} as const;
const assistantRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const channelRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const chatRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const entityRelationships = {
  workspace: [
    {
      sourceField: ["rootId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  trashWorkspace: [
    {
      sourceField: ["parentId"],
      destField: ["trashId"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  children: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "entity",
      cardinality: "many",
    },
  ],
  item: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "item",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const entityAccessRelationships = {
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const itemRelationships = {
  workspace: [
    {
      sourceField: ["rootId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  blob: [
    {
      sourceField: ["blobId"],
      destField: ["id"],
      destSchema: "blob",
      cardinality: "one",
    },
  ],
} as const;
const mcpPluginRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const messageRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  toolCalls: [
    {
      sourceField: ["id"],
      destField: ["messageId"],
      destSchema: "toolCall",
      cardinality: "many",
    },
  ],
  assistant: [
    {
      sourceField: ["rootId", "assistantId"],
      destField: ["rootId", "id"],
      destSchema: "assistant",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  entities: [
    {
      sourceField: ["rootId", "id"],
      destField: ["rootId", "messageId"],
      destSchema: "messageEntity",
      cardinality: "many",
    },
    {
      sourceField: ["rootId", "entityId"],
      destField: ["rootId", "id"],
      destSchema: "entity",
      cardinality: "many",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const modelRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  provider: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "provider",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const orderRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  plan: [
    {
      sourceField: ["planId"],
      destField: ["id"],
      destSchema: "plan",
      cardinality: "one",
    },
  ],
} as const;
const pageRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  patches: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "pagePatch",
      cardinality: "many",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const pagePatchRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  page: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "page",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const planRelationships = {
  prices: [
    {
      sourceField: ["id"],
      destField: ["planId"],
      destSchema: "planPrice",
      cardinality: "many",
    },
  ],
} as const;
const providerRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  models: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "model",
      cardinality: "many",
    },
  ],
} as const;
const searchRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  records: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "searchRecord",
      cardinality: "many",
    },
  ],
} as const;
const searchRecordRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  search: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "search",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const shortcutRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const toolCallRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const translationRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  records: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "translationRecord",
      cardinality: "many",
    },
  ],
} as const;
const translationRecordRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  translation: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "translation",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const usageRelationships = {
  member: [
    {
      sourceField: ["workspaceId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const userDataRelationships = {
  user: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const workspaceRelationships = {
  member: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  root: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  trash: [
    {
      sourceField: ["trashId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  plan: [
    {
      sourceField: ["planId"],
      destField: ["id"],
      destSchema: "plan",
      cardinality: "one",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "workspaceInvitation",
      cardinality: "many",
    },
  ],
} as const;
const workspaceInvitationRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  inviter: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    assistant: assistantTable,
    blob: blobTable,
    channel: channelTable,
    chat: chatTable,
    entity: entityTable,
    entityAccess: entityAccessTable,
    globalSettings: globalSettingsTable,
    item: itemTable,
    mcpPlugin: mcpPluginTable,
    member: memberTable,
    message: messageTable,
    messageEntity: messageEntityTable,
    model: modelTable,
    order: orderTable,
    page: pageTable,
    pagePatch: pagePatchTable,
    plan: planTable,
    planPrice: planPriceTable,
    provider: providerTable,
    search: searchTable,
    searchRecord: searchRecordTable,
    shortcut: shortcutTable,
    toolCall: toolCallTable,
    translation: translationTable,
    translationRecord: translationRecordTable,
    usage: usageTable,
    user: userTable,
    userData: userDataTable,
    workspace: workspaceTable,
    workspaceInvitation: workspaceInvitationTable,
  },
  relationships: {
    assistant: assistantRelationships,
    channel: channelRelationships,
    chat: chatRelationships,
    entity: entityRelationships,
    entityAccess: entityAccessRelationships,
    item: itemRelationships,
    mcpPlugin: mcpPluginRelationships,
    member: memberRelationships,
    message: messageRelationships,
    model: modelRelationships,
    order: orderRelationships,
    page: pageRelationships,
    pagePatch: pagePatchRelationships,
    plan: planRelationships,
    provider: providerRelationships,
    search: searchRelationships,
    searchRecord: searchRecordRelationships,
    shortcut: shortcutRelationships,
    toolCall: toolCallRelationships,
    translation: translationRelationships,
    translationRecord: translationRecordRelationships,
    usage: usageRelationships,
    userData: userDataRelationships,
    workspace: workspaceRelationships,
    workspaceInvitation: workspaceInvitationRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "assistant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Assistant = Row<(typeof schema)["tables"]["assistant"]>;
/**
 * Represents a row from the "blob" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Blob = Row<(typeof schema)["tables"]["blob"]>;
/**
 * Represents a row from the "channel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Channel = Row<(typeof schema)["tables"]["channel"]>;
/**
 * Represents a row from the "chat" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Chat = Row<(typeof schema)["tables"]["chat"]>;
/**
 * Represents a row from the "entity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Entity = Row<(typeof schema)["tables"]["entity"]>;
/**
 * Represents a row from the "entityAccess" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EntityAccess = Row<(typeof schema)["tables"]["entityAccess"]>;
/**
 * Represents a row from the "globalSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GlobalSetting = Row<(typeof schema)["tables"]["globalSettings"]>;
/**
 * Represents a row from the "item" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Item = Row<(typeof schema)["tables"]["item"]>;
/**
 * Represents a row from the "mcpPlugin" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type McpPlugin = Row<(typeof schema)["tables"]["mcpPlugin"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<(typeof schema)["tables"]["message"]>;
/**
 * Represents a row from the "messageEntity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MessageEntity = Row<(typeof schema)["tables"]["messageEntity"]>;
/**
 * Represents a row from the "model" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Model = Row<(typeof schema)["tables"]["model"]>;
/**
 * Represents a row from the "order" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Order = Row<(typeof schema)["tables"]["order"]>;
/**
 * Represents a row from the "page" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Page = Row<(typeof schema)["tables"]["page"]>;
/**
 * Represents a row from the "pagePatch" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PagePatch = Row<(typeof schema)["tables"]["pagePatch"]>;
/**
 * Represents a row from the "plan" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Plan = Row<(typeof schema)["tables"]["plan"]>;
/**
 * Represents a row from the "planPrice" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlanPrice = Row<(typeof schema)["tables"]["planPrice"]>;
/**
 * Represents a row from the "provider" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Provider = Row<(typeof schema)["tables"]["provider"]>;
/**
 * Represents a row from the "search" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Search = Row<(typeof schema)["tables"]["search"]>;
/**
 * Represents a row from the "searchRecord" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SearchRecord = Row<(typeof schema)["tables"]["searchRecord"]>;
/**
 * Represents a row from the "shortcut" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Shortcut = Row<(typeof schema)["tables"]["shortcut"]>;
/**
 * Represents a row from the "toolCall" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ToolCall = Row<(typeof schema)["tables"]["toolCall"]>;
/**
 * Represents a row from the "translation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Translation = Row<(typeof schema)["tables"]["translation"]>;
/**
 * Represents a row from the "translationRecord" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TranslationRecord = Row<
  (typeof schema)["tables"]["translationRecord"]
>;
/**
 * Represents a row from the "usage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Usage = Row<(typeof schema)["tables"]["usage"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "userData" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserDatum = Row<(typeof schema)["tables"]["userData"]>;
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>;
/**
 * Represents a row from the "workspaceInvitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkspaceInvitation = Row<
  (typeof schema)["tables"]["workspaceInvitation"]
>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
