// @generated drizzle-zero signature:sha256:05bb09db76d7f919ac56f6afd73a658a6891994c30f70c0bac5640b5fbdc8b24
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "../drizzle-zero.config";

export type AssistantStreamSettingsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "assistant",
  "streamSettings"
>;
export type ChatMsgTreeCustomType = ZeroCustomType<
  typeof zeroSchema,
  "chat",
  "msgTree"
>;
export type ChatMsgRouteCustomType = ZeroCustomType<
  typeof zeroSchema,
  "chat",
  "msgRoute"
>;
export type EntityConfCustomType = ZeroCustomType<
  typeof zeroSchema,
  "entity",
  "conf"
>;
export type MessageTypeCustomType = ZeroCustomType<
  typeof zeroSchema,
  "message",
  "type"
>;
export type MessageUsageCustomType = ZeroCustomType<
  typeof zeroSchema,
  "message",
  "usage"
>;
export type ModelSettingsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "model",
  "settings"
>;
export type ModelProviderOptionsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "model",
  "providerOptions"
>;
export type OrderProviderCustomType = ZeroCustomType<
  typeof zeroSchema,
  "order",
  "provider"
>;
export type ProviderSettingsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "provider",
  "settings"
>;
export type ToolCallResultCustomType = ZeroCustomType<
  typeof zeroSchema,
  "toolCall",
  "result"
>;
export type UserDataPerfsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "userData",
  "perfs"
>;
export type UserDataDataCustomType = ZeroCustomType<
  typeof zeroSchema,
  "userData",
  "data"
>;
export type WorkspacePaymentCustomType = ZeroCustomType<
  typeof zeroSchema,
  "workspace",
  "payment"
>;
export type WorkspacePerfsCustomType = ZeroCustomType<
  typeof zeroSchema,
  "workspace",
  "perfs"
>;

const assistantTable = {
  name: "assistant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    prompt: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    promptTemplate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    promptRole: {
      type: "string",
      optional: false,
      customType: null as unknown as "user" | "system",
    },
    contextNum: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    streamSettings: {
      type: "json",
      optional: false,
      customType: null as unknown as AssistantStreamSettingsCustomType,
    },
    plugins: {
      type: "json",
      optional: false,
      customType: null as unknown as string[],
    },
    modelId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const blobTable = {
  name: "blob",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sha256: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    size: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const channelTable = {
  name: "channel",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const chatTable = {
  name: "chat",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    msgTree: {
      type: "json",
      optional: false,
      customType: null as unknown as ChatMsgTreeCustomType,
    },
    msgRoute: {
      type: "json",
      optional: false,
      customType: null as unknown as ChatMsgRouteCustomType,
    },
    plugins: {
      type: "json",
      optional: true,
      customType: null as unknown as string[],
    },
    modelId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const entityTable = {
  name: "entity",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "chat"
        | "channel"
        | "assistant"
        | "page"
        | "provider"
        | "item"
        | "shortcut"
        | "search"
        | "translation"
        | "mcpPlugin"
        | "folder",
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as
        | { type: "svg"; name: string; hue?: number | undefined }
        | { type: "text"; text: string; hue?: number | undefined }
        | { type: "icon"; icon: string; hue?: number | undefined }
        | { type: "image"; itemId: string; hue?: number | undefined }
        | { type: "url"; url: string; hue?: number | undefined },
    },
    conf: {
      type: "json",
      optional: false,
      customType: null as unknown as EntityConfCustomType,
    },
    sortPriority: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    hidden: {
      type: "boolean",
      optional: false,
      customType: null as unknown as boolean,
    },
    pubRoot: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const entityAccessTable = {
  name: "entityAccess",
  columns: {
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    time: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["entityId", "userId"],
} as const;
const globalSettingsTable = {
  name: "globalSettings",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    defaultChatModel: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    defaultChatTitleModel: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    defaultTranslationModel: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    defaultSearchChatModel: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    freeModelReqLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    freeModelLimitWindow: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    maxWorkspacesPerUser: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    searchEngines: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    oauthProviders: {
      type: "json",
      optional: false,
      customType: null as unknown as string[],
    },
    tosLink: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    privacyPolicyLink: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const itemTable = {
  name: "item",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    text: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    language: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    blobId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    mimeType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const mcpPluginTable = {
  name: "mcpPlugin",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    enabled: {
      type: "boolean",
      optional: false,
      customType: null as unknown as boolean,
    },
    transport: {
      type: "json",
      optional: false,
      customType: null as unknown as { type: "http"; url: string },
    },
    requestTimeout: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    resetTimeoutOnProgress: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    keepAliveTimeout: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "member" | "owner" | "admin" | "guest",
    },
    leftDirId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const messageTable = {
  name: "message",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as MessageTypeCustomType,
    },
    assistantId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sentAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    editedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    text: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reasoning: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    warnings: {
      type: "json",
      optional: true,
      customType: null as unknown as string[],
    },
    usage: {
      type: "json",
      optional: true,
      customType: null as unknown as MessageUsageCustomType,
    },
    modelName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const messageEntityTable = {
  name: "messageEntity",
  columns: {
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["messageId", "entityId"],
} as const;
const modelTable = {
  name: "model",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    label: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    caption: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as
        | { type: "svg"; name: string; hue?: number | undefined }
        | { type: "text"; text: string; hue?: number | undefined }
        | { type: "icon"; icon: string; hue?: number | undefined }
        | { type: "image"; itemId: string; hue?: number | undefined }
        | { type: "url"; url: string; hue?: number | undefined },
    },
    inputTypes: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        user: string[];
        assistant: string[];
        tool: string[];
      },
    },
    settings: {
      type: "json",
      optional: false,
      customType: null as unknown as ModelSettingsCustomType,
    },
    inputPrice: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    outputPrice: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    providerOptions: {
      type: "json",
      optional: true,
      customType: null as unknown as ModelProviderOptionsCustomType,
    },
    sortPriority: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const orderTable = {
  name: "order",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    planInterval: {
      type: "string",
      optional: false,
      customType: null as unknown as "monthly" | "quarterly" | "yearly",
    },
    provider: {
      type: "json",
      optional: false,
      customType: null as unknown as OrderProviderCustomType,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const pageTable = {
  name: "page",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    text: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const pagePatchTable = {
  name: "pagePatch",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    patch: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const planTable = {
  name: "plan",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    maxMembers: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    storageLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    fileSizeLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    quotaLimit: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const planPriceTable = {
  name: "planPrice",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    enabled: {
      type: "boolean",
      optional: false,
      customType: null as unknown as boolean,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as "stripe" | "wxpay",
    },
    interval: {
      type: "string",
      optional: false,
      customType: null as unknown as "monthly" | "quarterly" | "yearly",
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    priceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const providerTable = {
  name: "provider",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    settings: {
      type: "json",
      optional: false,
      customType: null as unknown as ProviderSettingsCustomType,
    },
  },
  primaryKey: ["id"],
} as const;
const searchTable = {
  name: "search",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    currentIndex: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const searchRecordTable = {
  name: "searchRecord",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    q: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    results: {
      type: "json",
      optional: false,
      customType: null as unknown as {
        title: string;
        url: string;
        content: string;
      }[],
    },
  },
  primaryKey: ["id"],
} as const;
const shortcutTable = {
  name: "shortcut",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    dirId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "chat"
        | "channel"
        | "assistant"
        | "page"
        | "provider"
        | "item"
        | "shortcut"
        | "search"
        | "translation"
        | "mcpPlugin"
        | "folder",
    },
    action: {
      type: "string",
      optional: true,
      customType: null as unknown as "createNew" | "openLast",
    },
  },
  primaryKey: ["id"],
} as const;
const toolCallTable = {
  name: "toolCall",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    pluginId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    messageId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    input: {
      type: "json",
      optional: false,
      customType: null as unknown as ReadonlyJSONValue,
    },
    result: {
      type: "json",
      optional: true,
      customType: null as unknown as ToolCallResultCustomType,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as "calling" | "failed" | "completed",
    },
    error: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const translationTable = {
  name: "translation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    currentIndex: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const translationRecordTable = {
  name: "translationRecord",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    rootId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    input: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    output: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    from: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    to: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const usageTable = {
  name: "usage",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    modelName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    cost: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    details: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ban_expires",
    },
    twoFactorEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "two_factor_enabled",
    },
  },
  primaryKey: ["id"],
} as const;
const userDataTable = {
  name: "userData",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    lastWorkspaceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    perfs: {
      type: "json",
      optional: false,
      customType: null as unknown as UserDataPerfsCustomType,
    },
    data: {
      type: "json",
      optional: false,
      customType: null as unknown as UserDataDataCustomType,
    },
  },
  primaryKey: ["id"],
} as const;
const workspaceTable = {
  name: "workspace",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    avatar: {
      type: "json",
      optional: true,
      customType: null as unknown as
        | { type: "svg"; name: string; hue?: number | undefined }
        | { type: "text"; text: string; hue?: number | undefined }
        | { type: "icon"; icon: string; hue?: number | undefined }
        | { type: "image"; itemId: string; hue?: number | undefined }
        | { type: "url"; url: string; hue?: number | undefined },
    },
    ownerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    planId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    quotaUsed: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    resetAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    remainingMonths: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    payment: {
      type: "json",
      optional: true,
      customType: null as unknown as WorkspacePaymentCustomType,
    },
    storageUsed: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    trashId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    perfs: {
      type: "json",
      optional: false,
      customType: null as unknown as WorkspacePerfsCustomType,
    },
    defaultLeftDirId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const workspaceInvitationTable = {
  name: "workspaceInvitation",
  columns: {
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workspaceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "member" | "admin" | "guest",
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    remainingSeats: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["token"],
} as const;
const assistantRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const channelRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const chatRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "message",
      cardinality: "many",
    },
  ],
} as const;
const entityRelationships = {
  workspace: [
    {
      sourceField: ["rootId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  trashWorkspace: [
    {
      sourceField: ["parentId"],
      destField: ["trashId"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  children: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "entity",
      cardinality: "many",
    },
  ],
  item: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "item",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const entityAccessRelationships = {
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const itemRelationships = {
  workspace: [
    {
      sourceField: ["rootId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  blob: [
    {
      sourceField: ["blobId"],
      destField: ["id"],
      destSchema: "blob",
      cardinality: "one",
    },
  ],
} as const;
const mcpPluginRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const messageRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  toolCalls: [
    {
      sourceField: ["id"],
      destField: ["messageId"],
      destSchema: "toolCall",
      cardinality: "many",
    },
  ],
  assistant: [
    {
      sourceField: ["rootId", "assistantId"],
      destField: ["rootId", "id"],
      destSchema: "assistant",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  entities: [
    {
      sourceField: ["rootId", "id"],
      destField: ["rootId", "messageId"],
      destSchema: "messageEntity",
      cardinality: "many",
    },
    {
      sourceField: ["rootId", "entityId"],
      destField: ["rootId", "id"],
      destSchema: "entity",
      cardinality: "many",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const modelRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  provider: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "provider",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const orderRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  plan: [
    {
      sourceField: ["planId"],
      destField: ["id"],
      destSchema: "plan",
      cardinality: "one",
    },
  ],
} as const;
const pageRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  patches: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "pagePatch",
      cardinality: "many",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const pagePatchRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  page: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "page",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const planRelationships = {
  prices: [
    {
      sourceField: ["id"],
      destField: ["planId"],
      destSchema: "planPrice",
      cardinality: "many",
    },
  ],
} as const;
const planPriceRelationships = {
  plan: [
    {
      sourceField: ["planId"],
      destField: ["id"],
      destSchema: "plan",
      cardinality: "one",
    },
  ],
} as const;
const providerRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  models: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "model",
      cardinality: "many",
    },
  ],
} as const;
const searchRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  records: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "searchRecord",
      cardinality: "many",
    },
  ],
} as const;
const searchRecordRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  search: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "search",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const shortcutRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const toolCallRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  message: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["messageId"],
      destField: ["id"],
      destSchema: "message",
      cardinality: "one",
    },
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const translationRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  records: [
    {
      sourceField: ["id"],
      destField: ["entityId"],
      destSchema: "translationRecord",
      cardinality: "many",
    },
  ],
} as const;
const translationRecordRelationships = {
  member: [
    {
      sourceField: ["rootId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  translation: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "translation",
      cardinality: "one",
    },
  ],
  entity: [
    {
      sourceField: ["entityId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
} as const;
const usageRelationships = {
  member: [
    {
      sourceField: ["workspaceId"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const userDataRelationships = {
  user: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const workspaceRelationships = {
  member: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "one",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  root: [
    {
      sourceField: ["id"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  trash: [
    {
      sourceField: ["trashId"],
      destField: ["id"],
      destSchema: "entity",
      cardinality: "one",
    },
  ],
  plan: [
    {
      sourceField: ["planId"],
      destField: ["id"],
      destSchema: "plan",
      cardinality: "one",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["workspaceId"],
      destSchema: "workspaceInvitation",
      cardinality: "many",
    },
  ],
} as const;
const workspaceInvitationRelationships = {
  workspace: [
    {
      sourceField: ["workspaceId"],
      destField: ["id"],
      destSchema: "workspace",
      cardinality: "one",
    },
  ],
  inviter: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    assistant: assistantTable,
    blob: blobTable,
    channel: channelTable,
    chat: chatTable,
    entity: entityTable,
    entityAccess: entityAccessTable,
    globalSettings: globalSettingsTable,
    item: itemTable,
    mcpPlugin: mcpPluginTable,
    member: memberTable,
    message: messageTable,
    messageEntity: messageEntityTable,
    model: modelTable,
    order: orderTable,
    page: pageTable,
    pagePatch: pagePatchTable,
    plan: planTable,
    planPrice: planPriceTable,
    provider: providerTable,
    search: searchTable,
    searchRecord: searchRecordTable,
    shortcut: shortcutTable,
    toolCall: toolCallTable,
    translation: translationTable,
    translationRecord: translationRecordTable,
    usage: usageTable,
    user: userTable,
    userData: userDataTable,
    workspace: workspaceTable,
    workspaceInvitation: workspaceInvitationTable,
  },
  relationships: {
    assistant: assistantRelationships,
    channel: channelRelationships,
    chat: chatRelationships,
    entity: entityRelationships,
    entityAccess: entityAccessRelationships,
    item: itemRelationships,
    mcpPlugin: mcpPluginRelationships,
    member: memberRelationships,
    message: messageRelationships,
    model: modelRelationships,
    order: orderRelationships,
    page: pageRelationships,
    pagePatch: pagePatchRelationships,
    plan: planRelationships,
    planPrice: planPriceRelationships,
    provider: providerRelationships,
    search: searchRelationships,
    searchRecord: searchRecordRelationships,
    shortcut: shortcutRelationships,
    toolCall: toolCallRelationships,
    translation: translationRelationships,
    translationRecord: translationRecordRelationships,
    usage: usageRelationships,
    userData: userDataRelationships,
    workspace: workspaceRelationships,
    workspaceInvitation: workspaceInvitationRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "assistant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Assistant = Row<(typeof schema)["tables"]["assistant"]>;
/**
 * Represents a row from the "blob" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Blob = Row<(typeof schema)["tables"]["blob"]>;
/**
 * Represents a row from the "channel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Channel = Row<(typeof schema)["tables"]["channel"]>;
/**
 * Represents a row from the "chat" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Chat = Row<(typeof schema)["tables"]["chat"]>;
/**
 * Represents a row from the "entity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Entity = Row<(typeof schema)["tables"]["entity"]>;
/**
 * Represents a row from the "entityAccess" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EntityAccess = Row<(typeof schema)["tables"]["entityAccess"]>;
/**
 * Represents a row from the "globalSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GlobalSetting = Row<(typeof schema)["tables"]["globalSettings"]>;
/**
 * Represents a row from the "item" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Item = Row<(typeof schema)["tables"]["item"]>;
/**
 * Represents a row from the "mcpPlugin" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type McpPlugin = Row<(typeof schema)["tables"]["mcpPlugin"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "message" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Message = Row<(typeof schema)["tables"]["message"]>;
/**
 * Represents a row from the "messageEntity" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MessageEntity = Row<(typeof schema)["tables"]["messageEntity"]>;
/**
 * Represents a row from the "model" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Model = Row<(typeof schema)["tables"]["model"]>;
/**
 * Represents a row from the "order" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Order = Row<(typeof schema)["tables"]["order"]>;
/**
 * Represents a row from the "page" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Page = Row<(typeof schema)["tables"]["page"]>;
/**
 * Represents a row from the "pagePatch" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PagePatch = Row<(typeof schema)["tables"]["pagePatch"]>;
/**
 * Represents a row from the "plan" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Plan = Row<(typeof schema)["tables"]["plan"]>;
/**
 * Represents a row from the "planPrice" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PlanPrice = Row<(typeof schema)["tables"]["planPrice"]>;
/**
 * Represents a row from the "provider" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Provider = Row<(typeof schema)["tables"]["provider"]>;
/**
 * Represents a row from the "search" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Search = Row<(typeof schema)["tables"]["search"]>;
/**
 * Represents a row from the "searchRecord" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SearchRecord = Row<(typeof schema)["tables"]["searchRecord"]>;
/**
 * Represents a row from the "shortcut" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Shortcut = Row<(typeof schema)["tables"]["shortcut"]>;
/**
 * Represents a row from the "toolCall" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ToolCall = Row<(typeof schema)["tables"]["toolCall"]>;
/**
 * Represents a row from the "translation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Translation = Row<(typeof schema)["tables"]["translation"]>;
/**
 * Represents a row from the "translationRecord" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TranslationRecord = Row<
  (typeof schema)["tables"]["translationRecord"]
>;
/**
 * Represents a row from the "usage" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Usage = Row<(typeof schema)["tables"]["usage"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "userData" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UserDatum = Row<(typeof schema)["tables"]["userData"]>;
/**
 * Represents a row from the "workspace" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspace"]>;
/**
 * Represents a row from the "workspaceInvitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkspaceInvitation = Row<
  (typeof schema)["tables"]["workspaceInvitation"]
>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
